### ISSUE TITLE
FE production build size too large

### ISSUE THREAD

**Issue by Al-Pragliola** [sighupio/fury-dashboard#14]
Hi team!

We need to reduce the output of the production build of the front end, now it's over 20MB with few components; we tried using brotli webpack compression at build time but It breaks everything.
What we can do is trying to make a working configuration of brotli in webpack ( decrease also the binary size ) or we can introduce brotli compression in the go server ( decrease only network payload for the users )

**Comment by omissis** [comment]
resolved
